### ISSUE TITLE
Warning: Entity name not in that top-level of the response body

### ISSUE THREAD

**Issue by blahutka** [minimul/xero-api#2]
I'm not sure if it's Xero issue or this gem.
When I call resource `CISSettings` 

`GET https://api.xero.com/api.xro/2.0/Contacts/bd2270c3-8706-4c11-9cfb-000b551c3f51/CISSettings`

See docs `CIS Settings (UK) ` https://developer.xero.com/documentation/api/contacts 

I got this message
```
entity name not in that top-level of the response body: entity_name=Contacts
=> {"Id"=>"4327501d-482a-4b32-9c9a-df942e82d847", "Status"=>"OK", "ProviderName"=>"john+xero", "DateTimeUTC"=>"/Date(1568636775723)/", "CISSettings"=>[{"Rate"=>20, "CISEnabled"=>true}]}
```

**Comment by minimul** [comment]
It is just a warning message. See [here](https://github.com/minimul/xero-api/blob/01625310db315c01f78c1c4c6ced0e62741b4967/lib/xero/api/connection.rb#L87).

In these scenarios (no top level in the JSON response) the raw hash is being returned so you'll have to handle those scenarios "manually" so to speak.
